version: "3.8"

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: todo
      DB_USERNAME: root
      DB_PASSWORD: root

volumes:
  dbdata:
